import { Download } from "lucide-react";
import { buttonVariants } from "@/components/ui/button";
import { cn } from "@/lib/utils";

/**
 * "Download PDF" for a report.
 *
 * A plain link, not a button with a handler: the file is generated by a server
 * route from the same service the page used, so the browser only has to follow
 * a URL. The current period travels with it, which is what makes the PDF match
 * what is on screen.
 */
export function ReportPdfLink({
  href,
  period,
  label = "Download PDF",
}: {
  /** The report's PDF route, e.g. "/reports/balance-sheet/pdf". */
  href: string;
  period: { from: Date; to: Date };
  label?: string;
}) {
  const query = new URLSearchParams({
    from: period.from.toISOString().slice(0, 10),
    to: period.to.toISOString().slice(0, 10),
  });

  return (
    <a
      href={`${href}?${query.toString()}`}
      className={cn(buttonVariants({ size: "sm", variant: "outline" }), "rounded-full")}
    >
      <Download className="size-4" aria-hidden />
      {label}
    </a>
  );
}
